-- Watchkeeper Keep — pending_approvals table for Watchmaster manifest-bump
-- approval saga (M6.3.b).
--
-- Stores a snapshot of every M6.2.x manifest-bump tool invocation that
-- entered the lead-approval flow. The Watchmaster's tool call writes a
-- row with `state='pending'` carrying the original `params_json`
-- (snapshot of the request body); the M6.3.b InteractionDispatcher
-- terminal-transitions the row to `approved` or `rejected` when the
-- lead operator clicks the matching button on the approval card. On
-- `approved`, the dispatcher re-invokes the matching M6.2.x tool with
-- the snapshot params; on `rejected`, the row is the audit-of-record.
--
-- Columns:
--   * approval_token  — opaque PK (text). Generated by the M6.2.x tool
--                       caller (M6.3.c will own its cryptography); the
--                       dispatcher matches the action_id payload back
--                       to this row via DAO.Get.
--   * tool_name       — pinned closed-set vocabulary
--                       (`propose_spawn` | `adjust_personality` |
--                       `adjust_language` | `retire_watchkeeper`). The
--                       M6.3.b dispatcher branches on this value to
--                       pick the right replayer.
--   * params_json     — full request body snapshot, encoded as the
--                       caller's domain-specific shape. NEVER reflected
--                       on any audit row (PII discipline; M2b.7).
--   * state           — `pending` (initial), `approved`, or `rejected`
--                       (terminal). CHECK constraint enforces the
--                       closed set; transitions only `pending` →
--                       terminal (the DAO Resolve method gates the
--                       transition; the SQL is a defense-in-depth).
--   * requested_at    — when the row was inserted; defaults to now()
--                       so the M6.2.x tool does not need to thread a
--                       timestamp through.
--   * resolved_at     — NULL while `state='pending'`; populated to
--                       now() at terminal transition.
--
-- The table is intentionally simple — no FK to manifest, no FK to
-- watchkeeper. The approval saga is a state machine over an opaque
-- token, not a join surface. A future expirer (deferred from M6.3.b)
-- will sweep stale `pending` rows after a configurable window.
--
-- See `docs/ROADMAP-phase1.md` §M6 → M6.3 → M6.3.b.

-- +goose Up
CREATE TABLE watchkeeper.pending_approvals (
  approval_token text PRIMARY KEY,
  tool_name text NOT NULL,
  params_json jsonb NOT NULL,
  state text NOT NULL DEFAULT 'pending' CHECK (
    state IN ('pending', 'approved', 'rejected')
  ),
  requested_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz NULL
);

-- +goose Down
DROP TABLE IF EXISTS watchkeeper.pending_approvals;
